[application]
tailwind_output = "tmp/styles.css"

[bundle]
identifier = "com.wingedcap.app"
publisher = "wingedcap"
icon = [
   "icons/16x16.png",
   "icons/24x24.png",
   "icons/32x32.png",
   "icons/64x64.png",
   "icons/256x256.png",
   "icons/icon.icns",
   "icons/icon.ico"
]

[web.app]

# HTML title tag content
title = "Wingedcap App"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
